/**
 * Prompt vocabulary for brutalist architecture image generation.
 * All arrays of terms used to construct varied prompts.
 */

// Prefix applied to all building types in prompt construction
export const BUILDING_PREFIX = 'brutalist';

export const BUILDING_TYPES = [
  'civic center',
  'residential tower block',
  'museum of contemporary art',
  'monastery',
  'university library',
  'government headquarters',
  'concert hall',
  'railway station',
  'shopping complex',
  'hospital',
  'embassy',
  'apartment megastructure',
  'courthouse',
  'house of worship',
  'parliament building',
  'bus terminal',
  'sports arena',
  'power station',
  'research facility',
  'generic bureaucratic building',
  'observatory',
  'television broadcast center',
  'offshore platform',
  'naval outpost',
  'lighthouse complex',
  'municipal records archive',
  'central data processing center',
  'water treatment facility',
  'flood control administration complex',
  'telecommunications switching hub',
  'meteorological institute',
  'border control facility',
  'customs inspection hall',
  'national statistics bureau',
  'public works headquarters',
  'urban planning authority building',
  'civil defense bunker complex',
  'emergency coordination center',
  'energy grid control center',
  'materials testing laboratory',
  'nuclear research annex',
  'aerospace administration building',
  'satellite ground station',
  'cartographic institute',
  'geological survey headquarters',
  'hydrological research station',
  'national mint facility',
  'archives of state security',
  'central licensing authority',
  'public housing authority headquarters',
  'infrastructure maintenance depot',
  'strategic communications center',
  'national logistics coordination hub',
  'climate research institute',
  'urban resilience center',
  'records verification bureau',
  'central compliance office',
  'population registry headquarters',
  'identity documentation center',
  'information audit authority',
  'public communications monitoring facility',
  'resource rationing administration',
  'labor allocation office',
  'industrial oversight ministry',
  'permitted activities licensing hall',
  'civic conduct review board',
  'public order processing center',
  'administrative detention intake facility',
  'interrogation and evaluation complex',
  'data reconciliation office',
  'statistical normalization department',
  'supply chain enforcement depot',
  'central scheduling authority',
  'workforce productivity bureau',
  'materials requisition clearinghouse',
  'infrastructure compliance tribunal',
  'urban zoning enforcement office',
  'sanitation and waste accounting authority',
  'public utilities penalty administration',
  'energy consumption monitoring center',
  'central filing and microfilm archive',
  'communications blackout control office',
  'emergency powers administration building',
  'state maintenance coordination office',
  'civil obligations processing center',
];

export const LIGHTING_CONDITIONS = [
  'overcast sky',
  'foggy morning',
  'foggy night with distant lights',
  'golden hour sunlight',
  'harsh midday sun with deep shadows',
  'blue hour twilight',
  'dramatic storm clouds',
  'diffused light through haze',
  'pale winter light',
  'soft dawn light',
  'moonlit night scene',
  'backlit silhouette',
  'dappled light through clouds',
    'heavy rainstorm with diffuse concrete reflections',
  'tornado forming on the distant horizon',
  'aurora borealis illuminating low cloud cover',
  'harsh glare of rotating searchlights',
  'intermittent lightning flashes behind storm clouds',
  'acidic orange smog-filtered sunlight',
  'snowstorm with light swallowed by falling snow',
  'dense fog pierced by sodium vapor lights',
  'cold moonlight broken by fast-moving clouds',
  'eclipse-darkened daylight',
  'post-rain twilight with reflective pavement glow',
  'floodlights cutting through airborne dust',
  'electrical substation arc-light glow',
  'industrial flare stacks lighting the night sky',
  'backlit thunderheads with silver linings',
  'low winter sun casting kilometer-long shadows',
  'nighttime illuminated only by emergency lighting',
  'ashen daylight under volcanic cloud cover',
  'high-altitude cirrus scattering pale sunlight',
  'searchlight beams crisscrossing low clouds',
  'bioluminescent auroral haze',
  'dawn light filtered through heavy pollution',
  'overhead sky glowing from unseen city lights',
  'strobing warning beacons in dense mist',
  'sunset refracted through ice crystals',
  'infrared-style heat haze lighting',
  'static-charged atmosphere before a storm break',
  'radio tower obstruction lights blinking rhythmically',
  'backscatter glow from distant explosions',
  'unnaturally flat light under total cloud saturation',
];

export const STYLISTIC_ELEMENTS = [
  'raw board-formed concrete texture',
  'monolithic geometric forms',
  'high contrast shadows',
  'film grain aesthetic',
  'weathered concrete patina',
  'repetitive window patterns',
  'cantilevered volumes',
  'exposed structural elements',
  'massive concrete pillars',
  'brutalist stairways and walkways',
  'geometric skylights',
  'deep recessed windows',
  'angular concrete balconies',
  'textured concrete panels',
  'imposing scale against human figures',
  'dramatic negative space',
  'fortress-like walls',
  'monumental entrance portal',
  'endlessly repeating modular facades',
  'oppressive symmetry enforced across all elevations',
  'sealed surfaces with no visible points of entry',
  'window apertures scaled below human proportion',
  'corridors implied by external rhythm but never revealed',
  'structural over-determination with redundant supports',
  'brutal overexpression of load-bearing logic',
  'forced perspective exaggerating verticality',
  'mechanical regularity with no visual hierarchy',
  'architecture that dwarfs circulation elements',
  'non-ornamental articulation used as intimidation',
  'voids carved with surgical precision',
  'relentless alignment of seams and joints',
  'architectural indifference to site or context',
  'recessed light wells that never reach the ground',
  'heavy overhangs that threaten collapse without explanation',
  'walls thick enough to suggest interior worlds',
  'facades that suggest infinite continuation beyond frame',
  'entrances scaled for vehicles rather than people',
  'window grids that imply surveillance rather than view',
  'deliberate denial of human-scale reference points',
  'compression of space through massive framing elements',
  'architecture as diagram made physical',
  'hyper-rational layout visible from exterior',
  'massive blank planes interrupted only by service penetrations',
  'subordination of circulation to structure',
  'building mass read as a single unbroken decision',
  'repetition approaching visual hypnosis',
  'form language that implies regulation without signage',
  'an overall sense of inevitability rather than design',
];

export const MASSING_ARCHETYPES = [
  'stacked slab megastructure',
  'stepped ziggurat massing',
  'cantilevered podium with tower',
  'monolithic block with carved voids',
  'terraced cascade of concrete plates',
  'ring atrium with heavy buttresses',
  'skybridge-linked volumes',
  'fortress-like perimeter block',
  'inverted pyramid form',
  'clustered tower composition',
  'endless linear slab extending beyond frame',
  'tiered megaplatform supporting secondary volumes',
  'solid plinth pierced by vertical service shafts',
  'interlocking orthogonal volumes with no dominant axis',
  'sunken mass embedded below grade with exposed upper decks',
  'perimeter wall enclosing an inaccessible core',
  'massive podium consuming the entire site footprint',
  'vertical extrusion of a single floor plate',
  'fractured monolith split by narrow light voids',
  'concentric rings of increasing density',
  'asymmetric mass balanced through counterweight volumes',
  'overlapping plates compressed into a single form',
  'central void surrounded by continuous built mass',
  'cascading setbacks driven by structural load paths',
  'superstructure resting on oversized pylons',
  'nested volumes locked into a rigid hierarchy',
  'horizontal megablock with parasitic towers',
  'tower emerging from an impenetrable base',
  'repetitive bar forms fused into a unified mass',
  'mass organized as a three-dimensional grid',
  'sheared block suggesting tectonic displacement',
  'megastructure wrapped around a voided courtyard',
  'elevated slab hovering above a shadowed undercroft',
  'radial massing converging on a central core',
  'deep-plan block with minimal external articulation',
  'stratified layers of unequal thickness',
  'continuous mass punctured only by service cuts',
  'form derived from circulation stacked vertically',
  'building read as infrastructure rather than object',
  'total massing that denies distinction between base and tower',
];

export const CONCRETE_EXPRESSIONS = [
  'board-formed concrete with visible shuttering marks',
  'bush-hammered concrete finish',
  'ribbed concrete with tie-hole grid',
  'raw cast-in-place concrete with exposed aggregate',
  'weathered concrete with water staining',
  'textured precast concrete panels',
  'smooth poured concrete surfaces',
  'corrugated concrete cladding',
  'over-poured concrete with visible cold joints',
  'formwork-imprinted concrete with irregular panel seams',
  'slag-infused concrete with darkened tonal variation',
  'patch-repaired concrete bearing scars of intervention',
  'carbon-stained concrete from decades of exhaust exposure',
  'spalled concrete revealing embedded rebar shadows',
  'polished concrete worn smooth by institutional traffic',
  'sandblasted concrete with aggressively eroded surface',
  'layered concrete pours with stratified lift lines',
  'post-tensioned concrete with exposed anchor plates',
  'concrete surfaces mottled by inconsistent curing',
  'brutal joint articulation emphasizing panel separation',
  'heavy precast elements with exaggerated chamfered edges',
  'concrete darkened by persistent moisture and algae growth',
  'asphalt-adjacent concrete stained by oil and runoff',
  'cement-rich concrete with unnatural pale opacity',
  'fiber-reinforced concrete with visible filament texture',
  'monolithic pours interrupted by emergency cut lines',
  'concrete scarred by removed temporary structures',
  'surface-burned concrete from form release agents',
  'concrete pocked by tie-rod recesses and plugs',
  'aggregate-forward concrete with oversized stone inclusions',
  'repetitive precast modules with manufacturing variance',
  'concrete bearing ghost outlines of removed signage',
  'chemically etched concrete with matte, lifeless finish',
  'concrete seams sealed with tar-black expansion joints',
  'cast concrete bearing alignment marks and construction codes',
  'concrete with frost damage and micro-fracturing',
  'overbuilt concrete sections suggesting redundant strength',
  'unfinished concrete edges left deliberately exposed',
];

export const FENESTRATION_PATTERNS = [
  'deep punched window openings',
  'narrow vertical slot windows',
  'repetitive modular window grid',
  'recessed ribbon glazing under deep overhangs',
  'clerestory band windows',
  'concrete brise-soleil sun shading',
  'irregular asymmetric window placement',
  'massive floor-to-ceiling glazing bays',
  'windowless facades interrupted only by service apertures',
  'horizontally compressed slit windows at irregular intervals',
  'deeply recessed openings casting permanent shadow wells',
  'fenestration scaled for machinery rather than occupants',
  'stacked observation windows with opaque spandrels',
  'small square apertures in rigid Cartesian alignment',
  'continuous ventilation slots disguised as windows',
  'glazing set flush behind thick structural frames',
  'repetitive viewing ports suggesting inspection points',
  'windows clustered only at uppermost levels',
  'deep-set corner windows denying panoramic views',
  'fenestration partially occluded by external structural fins',
  'alternating window-and-wall rhythm enforcing visual monotony',
  'high-level ribbon openings admitting light but no sightlines',
  'gridded apertures implying surveillance arrays',
  'fenestration terminating abruptly at structural breaks',
  'deep embrasure-like window reveals',
  'inset glazing buried within concrete thickness',
  'windows expressed as cuts rather than openings',
  'opaque glazing with indistinct interior visibility',
  'window patterns broken only by vertical service risers',
  'fenestration subordinated entirely to structural grid',
  'irregularly infilled former window openings',
  'apertures suggesting retrofitted compliance upgrades',
  'openings aligned strictly with internal circulation paths',
  'windows framed by exaggerated concrete margins',
  'narrow horizontal vision bands at ceiling height',
  'fenestration suggesting defensive fortification',
  'view-denying apertures admitting only ambient light',
  'openings that imply observation without reciprocity',
];

export const CONTEXTS = [
  'in a stark civic plaza with broad steps',
  'on a coastal cliff with sea mist',
  'in a dense urban canyon between towers',
  'in an alpine valley under heavy clouds',
  'on the edge of a desert plateau',
  'beside a concrete riverwalk',
  'at the center of a university campus',
  'in an empty concrete landscape',
  'surrounded by overgrown vegetation',
  'in a sparse industrial zone',
  'overlooking a grey cityscape',
  'amid other brutalist structures',
  'at the terminus of an unfinished transit corridor',
  'between decommissioned infrastructure and new construction',
  'in a buffer zone separating districts of unequal status',
  'at the edge of a partially abandoned administrative quarter',
  'in a floodplain cleared of prior habitation',
  'adjacent to obsolete infrastructure awaiting removal',
  'within a restricted zone with no visible access points',
  'on reclaimed land still bearing construction scars',
  'in a provisional civic zone never formally completed',
  'surrounded by temporary fencing long since deteriorated',
  'at the boundary between urban fabric and exclusion zone',
  'in a vast paved expanse without signage or orientation',
  'among structures awaiting reassignment or demolition',
  'on a site cleared after an unspecified incident',
  'between overlapping but incompatible zoning regimes',
  'in a landscape shaped by regulations rather than use',
  'within an infrastructural no-man’s-land',
  'at the end of a ceremonial axis no longer used',
  'in a zone designated for future expansion that never occurred',
  'surrounded by residual service roads and hardstand',
  'in an administrative void between jurisdictions',
  'on a former greenbelt converted to civic use',
  'adjacent to a silent interchange with no traffic',
  'in an environment stripped of informal human activity',
  'at the edge of mapped territory with incomplete records',
  'among provisional buildings made permanent by neglect',
  'in a place defined only by planning documents',
  'on land stabilized but never landscaped',
  'within a corridor reserved for unspecified future use',
  'in a space that feels temporarily permanent',
];

export const CAMERA_ANGLES = [
  'low-angle heroic perspective',
  'dramatic worms-eye view looking up',
  'eye-level documentary framing',
  'aerial perspective from above',
  'three-quarter architectural view',
  'Dutch angle tilt',
  'distant establishing shot',
  'symmetrical centered composition',
  'tilt-shift miniature effect',
  'axial push-in along a rigid central axis',
  'severe one-point perspective with vanishing-point dominance',
  'low-angle tracking shot skimming along the ground plane',
  'off-center composition under oppressive negative space',
  'high-angle surveillance-like observation',
  'static frame with implied violent motion outside view',
  'extreme wide-angle exaggerating spatial distortion',
  'tight framing that truncates the building edges',
  'camera pressed close to facade, denying full form',
  'long-lens compression flattening mass and depth',
  'diagonal composition implying imbalance and momentum',
  'locked-off frame with brutal symmetry',
  'slow lateral pan revealing repetitive massing',
  'vertiginous upward tilt emphasizing infinite height',
  'oblique angle suggesting accidental discovery',
  'camera trapped beneath overhangs and structural shadows',
  'foreground obstruction partially occluding the subject',
  'center-weighted composition resisting narrative flow',
  'perspective aligned with service corridors or access ramps',
  'wide shot with tiny human figures pinned to the bottom edge',
  'asymmetric framing that never resolves into balance',
  'viewpoint aligned with mechanical or infrastructural paths',
  'static shot held past the point of comfort',
  'forced depth created by receding structural grids',
  'camera positioned at the threshold of entry without crossing',
  'rigid frontal elevation treated as confrontational',
  'compressed vertical framing exaggerating confinement',
  'perspective suggesting the camera is being observed',
  'composition dominated by a single immovable mass',
  'framing that implies continuation beyond the image boundary',
];

export const REGIONAL_STYLES = [
  'Soviet brutalist style',
  'British brutalist tradition',
  'Japanese metabolist influence',
  'Brazilian concrete modernism',
  'Yugoslav monument aesthetic',
  'Eastern European socialist architecture',
  'Scandinavian concrete minimalism',
  'American institutional brutalism',
  'French béton brut style',
    // Widely recognized / academically grounded
  'Italian neorealist brutalism',
  'German postwar reconstruction brutalism',
  'Swiss infrastructural brutalism',
  'Israeli desert brutalism',
  'Canadian late-modern institutional brutalism',
  'Australian civic brutalism',
  'South African apartheid-era brutalism',
  'Indian post-independence concrete modernism',
  'Mexican monumental modernism in concrete',
  'Spanish late-Franco institutional brutalism',
  'Dutch structuralist brutalism',
  'Belgian béton brutal',
  'Austrian administrative brutalism',
  'Czech and Slovak late-socialist brutalism',
  'Polish infrastructural brutalism',
  'Hungarian state modernism',
  'Romanian civic brutalism',
  'Argentinian institutional modernism',
  'Chilean concrete modernism',

  // Functionally defined but real-world-adjacent
  'postwar educational brutalism',
  'municipal infrastructure brutalism',
  'defense and civil protection brutalism',
  'transport authority brutalism',
  'welfare-state institutional brutalism',

  // Low-temperature invented extrapolations (plausible, pragmatic)
  'late-bureaucratic brutalism',
  'systems-first brutalism',
  'permanent-temporary brutalism',
  'overbuilt safety-factor brutalism',
  'administrative megastructure brutalism',
];

export const CONDITIONS = [
  'pristine and newly constructed',
  'slightly weathered with age',
  'aged with concrete staining and patina',
  'partially overgrown with moss and lichen',
  'showing dignified signs of urban wear',
  'rain-soaked with wet reflections',
  'sun-bleached and dusty',
  'immaculately maintained with no visible wear',
  'uniformly cleaned to institutional standards',
  'surfaces sealed and impervious to staining',
  'precisely finished with no construction irregularities',
  'recently pressure-washed and visually sterile',
  'maintained under continuous inspection protocols',
  'free of ornament, signage, or informal markings',
  'material surfaces optimized for longevity over comfort',
  'operating at peak functional condition',
];

export const PHOTO_STYLES = [
  '35mm architectural photography',
  'medium format film photograph',
  '1970s documentary photography style',
  'contemporary fine art photography',
  'muted desaturated color palette',
  'high dynamic range photograph',
  'subtle Kodak Portra color rendering',
  'cool daylight color balance',
  'large-format architectural survey photography',
  'forensic documentation photography',
  'state-commissioned institutional photography',
  'neutral color science with suppressed saturation',
  'high-contrast black-and-white with crushed midtones',
  'flat overcast exposure prioritizing surface detail',
  'archival contact-print aesthetic',
  'orthographic elevation-style framing',
  'clinical sharpness with deep depth of field',
  'low-ISO fine-grain realism',
  'cool fluorescent-balanced interior spill',
  'photography optimized for record-keeping rather than mood',
  'high-sun coastal architectural photography',
  'hard midday light with saturated skies',
  'ultra-clean tropical daylight exposure',
  'bold primary-color contrast against raw concrete',
  'graphic shadow patterns under intense sunlight',
  'high-clarity digital capture with vivid color separation',
  'azure-sky backdrop with stark concrete foreground',
  'sun-bleached highlights with deep cobalt shadows',
  'architectural photography optimized for tourism publications',
  'brutalist forms under resort-grade lighting conditions',
  'bright cyan and sand-toned color palette',
  'editorial infrastructure photography with pop-art contrast',
  'sunlit concrete with exaggerated tonal separation',
  'high-gloss contemporary color grading',
  'hyper-legible geometry under cloudless skies',
];

export const MUTATIONS = [
  'extreme fog with diffuse contrast',
  'light rain with wet surfaces',
  'heavy atmospheric haze',
  'dramatic long shadows',
  'minimalist empty foreground',
  'fresh snow dusting',
  'low-lying ground mist obscuring base conditions',
  'overcast sky producing uniform flat light',
  'backlit atmosphere reducing facade detail',
  'specular glare from polished or wet surfaces',
  'particulate-laden air softening distant edges',
  'long exposure smoothing motion artifacts',
  'foreground occluded by infrastructural elements',
  'monochromatic atmospheric cast',
  'subtle motion blur from environmental movement',
  'shadow compression under diffuse lighting',
  'high-altitude haze flattening depth cues',
  'visual noise from film grain or sensor texture',
];

export const BASE_PROMPT_SUFFIX =
  'architectural photography, professional composition, ' +
  'no text, no watermarks, highly detailed, photorealistic';
